ampy -p COM3 rm boot.py
ampy -p COM3 rm main.py
ampy -p COM3 rm Screen.py
ampy -p COM3 rm FileHandler.py
ampy -p COM3 rm message.txt
ampy -p COM3 put boot.py
ampy -p COM3 put Screen.py
ampy -p COM3 put FileHandler.py
ampy -p COM3 put main.py
ampy -p COM3 put message.txt
